name: Test Cortex
on:
  push:
    branches: [ master, v6 ]
  pull_request:
    branches: [ master, v6 ]
jobs:
  test-cortex:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        pip install pylint pytest
    - name: Lint with pylint
      run: ./run_pylint.sh
